language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - yarn build
  - yarn test
deploy:
  - provider: surge
    project: ./build/
    domain: clemensbros.surge.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: surge
    project: ./build/
    domain: clemensbros-stage.surge.sh
    skip_cleanup: true
    on:
      branch: develop